### ISSUE TITLE
get_heroes and get_game_items error

### ISSUE THREAD

**Issue by joshuaduffy** [joshuaduffy/dota2api#15]
Traceback (most recent call last):
      File "<input>", line 1, in <module>
      File "C:\Users\Joshua Duffy\Documents\GitHub\dota2api\dota2api\__init__.py", line 151, in     get_game_items
        return response.build(req, url)
      File "C:\Users\Joshua Duffy\Documents\GitHub\dota2api\dota2api\src\response.py", line 20, in build
       raise APIError(req_resp['result']['statusDetail'])
    KeyError: 'statusDetail'

**Comment by joshuaduffy** [comment]
Fixed - get_game_items(), get_heroes() and get_tournament_prize_pool() return a status of 200, not 1 like the other calls.
